cmake_minimum_required(VERSION 3.13)
include($ENV{PICO_SDK_PATH}/external/pico_sdk_import.cmake)
project(xgo_p5_usbphy_diagnostic C CXX ASM)
set(CMAKE_C_STANDARD 11)
set(CMAKE_CXX_STANDARD 17)
pico_sdk_init()
add_executable(xgo_p5_usbphy_diagnostic main.c)
target_link_libraries(xgo_p5_usbphy_diagnostic pico_stdlib)
pico_enable_stdio_usb(xgo_p5_usbphy_diagnostic 0)
pico_enable_stdio_uart(xgo_p5_usbphy_diagnostic 0)
pico_add_extra_outputs(xgo_p5_usbphy_diagnostic)
