cmake_minimum_required(VERSION 3.13)
include($ENV{PICO_SDK_PATH}/external/pico_sdk_import.cmake)
project(xgo_p1_fixed_r C CXX ASM)
set(CMAKE_C_STANDARD 11)
set(CMAKE_CXX_STANDARD 17)
pico_sdk_init()
add_executable(xgo_p1_fixed_r main.c)
pico_generate_pio_header(xgo_p1_fixed_r ${CMAKE_CURRENT_LIST_DIR}/xgo_fixed_r.pio)
target_link_libraries(xgo_p1_fixed_r pico_stdlib hardware_pio)
pico_enable_stdio_usb(xgo_p1_fixed_r 1)
pico_enable_stdio_uart(xgo_p1_fixed_r 0)
pico_add_extra_outputs(xgo_p1_fixed_r)
